ENTITY_LIST = [
'Abby',
'Al',
'Al Kostelic',
'Al Minser',
'Al Pacino',
'Alan',
'Albert Einstein',
'Alex',
'All',
'Amber',
'Amger',
'Andie McDowell',
'Andr',
'Andre',
'Andrea',
'Andrea\'s friend',
'Andrew',
'Angela Delvecchio',
'Annabelle',
'Artelle',
'Ashley',
'Aunt Edna',
'Aunt Iris',
'Aunt Lillian',
'Aunt Phyllis',
'Aunt Syl',
'Aurora',
'Avery',
'Barbara',
'Barry',
'Ben',
'Bernie Spellman',
'Best Man',
'Bethel',
'Betty',
'Big Bully',
'Bill Clinton',
'Bill Dreskin\'s father',
'Billy Dreskin',
'Bing',
'Bishop Tutu',
'Black Bart',
'Bob',
'Bobby Rush',
'Boss Man Bing',
'Brad',
'Braverman',
'Brent Mussberger',
'Brian',
'Brittany',
'Carl',
'Carol Willick',
'Carol and Susan\'s caterer',
'Carol\'s grandmother',
'Caroline',
'Casey',
'Casting Guy',
'Cathy Bates',
'Celia',
'Chandler Bing',
'Chandler\'s date',
'Chandler\'s date\'s husband',
'Chandler\'s date\'s husband\'s secretary',
'Chandler\'s ex-girlfriend',
'Chandler\'s girlfriend',
'Chandler\'s imaginary friend',
'Chandler\'s secretary',
'Charles Bing',
'Chrissy',
'Christine',
'Coma Guy',
'Customer',
'Damone',
'Dan',
'Dana',
'Danielle',
'Danny Arshak',
'Daryl Hannah',
'Dave Thomas',
'David Hasselhof',
'Deb',
'Debbie',
'Debra',
'Dee',
'Demi Moore',
'Denise DeMarco',
'Dick Clark',
'Dillon',
'Director',
'Director\'s Assistant',
'Donna Reid',
'Dorothy',
'Dr. Baldhara',
'Dr. Bazida',
'Dr. Drake Remoray',
'Dr. Flanen',
'Dr. Franzblau',
'Dr. Horton',
'Dr. Mitchell',
'Dr. Oberman',
'Dr. Remore',
'Dr. Rosen',
'Dr. Wong',
'Drew Barrymore',
'Dudley Moore',
'Duncan',
'Ed',
'Ed Begley',
'Eddie',
'Eddie Minowick',
'Eddie Moskowitz',
'Eddie\'s ex-girlfriend',
'Eddie\'s previous roommate',
'Emma',
'Eric Estrada',
'Eric Prower',
'Erica Ford',
'Ernest Borgnine',
'Err',
'Error',
'Estelle',
'Estelle Leonard',
'Esther Livingston',
'Ethan',
'Evelyn Dermer',
'Ewing',
'Fake Monica',
'Fleischman',
'Flench',
'Flight Attendant',
'Florence Henderson',
'Foghorn Leghorn',
'Frank Buffay',
'Frankie',
'Frannie',
'Freud',
'Fun Bobby',
'Gail',
'George',
'George Bailey',
'George Stephanopoulos',
'Girl',
'Girls',
'Gloria Tribbiani',
'Grandmother',
'Gunther',
'Guy',
'Guy 1',
'Guys',
'Hannibal Lecter',
'Helen',
'Henry',
'Hombre Man',
'Howard',
'Huey Lewis',
'Hugh Grant',
'Ingrid Bergman',
'Intercom',
'Interviewer',
'Ive',
'Jack',
'Jack 1',
'Jack 2',
'Jack Geller',
'Jade',
'James Bond',
'Jamie',
'Jane',
'Janice',
'Janitor',
'Jason Costalano',
'Jason Hurley',
'Jay Leno',
'Jeannie',
'Jill',
'Jill Goodacre',
'Jill Green',
'Jill\'s mom',
'Jim Crochee',
'Jimmy Hauser',
'Joan Collins',
'Joanne',
'Joanne\'s father',
'Joey Tribbiani',
'Joey Tribbiani Sr.',
'Joey\'s Co-star',
'Joey\'s cousin',
'Joey\'s date',
'Joey\'s date\'s friend',
'Joey\'s tailor',
'John Savage',
'John Voit',
'Johnny Shapiro',
'Jordie',
'Joseph Stalin',
'Judy Geller',
'Judy Jetson',
'Julie',
'Julie\'s friend',
'Karen',
'Kid',
'Kip',
'Kristin',
'Laurie Schaffer',
'Leon',
'Leonard Green',
'Leroy',
'Leslie',
'Liam Neeson',
'Lifson',
'Lily Buffay',
'Linda',
'Lipson',
'Little Bully',
'Lizzie',
'Lola',
'Lori',
'Lorne Green',
'Lorraine',
'Lowell',
'Luisa',
'Luisa\'s supervisor',
'Lydia',
'Lydia\'s baby',
'Lydia\'s husband',
'Lydia\'s mom',
'Malibu Ken',
'Man',
'Man 1',
'Man 2',
'Marcel',
'Marcel Marceau',
'Mark',
'Marsha',
'Marty',
'Mary Tyler Moore',
'Max',
'Melanie',
'Messier',
'Michael',
'Michelle',
'Milton',
'Mindy',
'Mira',
'Miss Buffay',
'Miss Crankypants',
'Miss Kitty',
'Moncia',
'Monica Geller',
'Monica\'s ex-boyfriend',
'Monica\'s grandmother',
'Morly Safer',
'Mother Theresa',
'Mover',
'Mr. Adelman',
'Mr. Clean',
'Mr. Douglas',
'Mr. Greene',
'Mr. Heckles',
'Mr. Peanut',
'Mr. Ratstatter',
'Mr. Roger',
'Mr. Roper',
'Mr. Salty',
'Mr. Treeger',
'Mr. Tribbiani',
'Mr. Wineburg',
'Mrs. Adelman',
'Mrs. Bing',
'Mrs. Buffay',
'Mrs. Cobb',
'Mrs. Geller',
'Mrs. Green',
'Mrs. Greene',
'Mrs. Tribbiani',
'Mrs. Wallace',
'Mrs. Wallace\'s sister',
'Mrs. Wineburg',
'Ms. Thomas',
'Nathan',
'Nina Bookbinder',
'Norman Mailer',
'Nurse',
'Paolo',
'Paul',
'Paul\'s ex-girlfriend',
'Paula',
'Paulo',
'Person 1',
'Person 2',
'Pete',
'Pete Carney',
'Phoebe Buffay',
'Phoebe and Rachel',
'Phoebe\'s Assistant',
'Phoebe\'s Friends',
'Phoebe\'s boyfriend',
'Phoebe\'s date',
'Phoebe\'s friend',
'Phoebe\'s grandmother',
'Phoebe\'s grandmother\'s boyfriend',
'Phoebe\'s hairdresser',
'Phoebe\'s stepfather',
'Phoebe, Joey, and Ross',
'Pizza Guy',
'Producer',
'Rachel Green',
'Rachel and Phoebe',
'Rachel\'s date',
'Rachel\'s friend',
'Rachel\'s interviewer',
'Rachel\'s interviewer\'s cousin',
'Rachel\'s sister',
'Radio',
'Ramone',
'Randy Brown',
'Receptionist',
'Richard',
'Richard Burke',
'Richard\'s son',
'Rick',
'Rob',
'Rob Dohnen',
'Rob Roy',
'Robbie',
'Robert Pillman',
'Rod Steiger',
'Rodney McDowell',
'Rodrigo',
'Roger',
'Roland',
'Rona',
'Ronni Rappelano',
'Rose',
'Rose Marie',
'Ross Geller',
'Ross\' date',
'Ross\' grandmother',
'Russ',
'Ryan',
'Sandra Green',
'Sandy',
'Scott Alexander',
'Security Guard',
'Shannon Cooper',
'Shelley',
'Shirley',
'Sidney Marks',
'Silvian',
'Soupy Sales',
'Spike Lee',
'Stacy Roth',
'Steffi Graf',
'Stella Niedman',
'Stephanie',
'Steve',
'Store Guy',
'Stranger',
'Susan Bunch',
'Susan Sallidor',
'Susie',
'Tanya',
'Tattoo Artist',
'Teacher',
'Terry',
'The Guys',
'The Whole Party',
'Tilly',
'Tina',
'Tina\'s husband',
'Toby',
'Tommy Rollerson',
'Tony',
'Tony DeMarco',
'Tony Randall',
'Tova Borgnine',
'Tracy',
'Trainer',
'Travis',
'Tso',
'Ugly Naked Guy',
'Uma Thurman',
'Uncle Freddie',
'Uncle Sal',
'Uncle Sal\'s wife',
'Underdog',
'Unknown',
'Ursula',
'Van Damme',
'Vidal Buffay',
'Waiter',
'Waitress',
'Warren Beatty',
'Wedding Planner',
'Wendy',
'Weve',
'Woman',
'Woman 1',
'Yamaguchi',
'Yasmine Blepe',
'Young Ethan'
]

def get_index(character) : 
	if character in ENTITY_LIST :
		return ENTITY_LIST.index(character)
	else:
		return 0